### ISSUE TITLE
import fails on Win10 with Python 3.8 and scipy 1.4.1 on fresh install

### ISSUE THREAD

**Issue by twomagpi** [publichealthengland/pygom#33]
Via Josh Lau:
"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\__init__.py", line 8, in <module>
    from .loss import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\loss\__init__.py", line 7, in <module>
    from pygom.loss.confidence_interval import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\loss\confidence_interval.py", line 23, in <module>
    from pygom.model._model_errors import EstimateError, InputError
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\model\__init__.py", line 11, in <module>
    from .epi_analysis import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\model\epi_analysis.py", line 11, in <module>
    from .simulate import SimulateOde
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\model\simulate.py", line 19, in <module>
    from .stochastic_simulation import cle, exact, firstReaction, tauLeap, hybrid
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygom\model\stochastic_simulation.py", line 18, in <module>
    from ._tau_leap import _cy_test_tau_leap_safety
  File "pygom\model\_tau_leap.pyx", line 1, in init pygom.model._tau_leap
ImportError: scipy.special.cython_special does not export expected C function __pyx_fuse_0pdtr"

**Comment by twomagpi** [comment]
Think this now works with 0.1.7

Will open a new issue if this persists
